name: "构建 Docker 镜像"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: 登录 Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建并推送
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nezha-agent:latest
            ${{ secrets.DOCKER_USERNAME }}/nezha-agent:${{ github.sha }}